services:
  # Backend service 01
  back-01:
    build:
      context: .
      dockerfile: back/Dockerfile
    container_name: back-01
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      HOST_TAG: back-01
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.125"
          memory: 64M

  # Backend service 02
  back-02:
    build:
      context: .
      dockerfile: back/Dockerfile
    container_name: back-02
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      HOST_TAG: back-02
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.250"
          memory: 128M

  # Backend service 03
  back-03:
    build:
      context: .
      dockerfile: back/Dockerfile
    container_name: back-03
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      HOST_TAG: back-03
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.250"
          memory: 256M

  # Nginx load balancer
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - back-01
      # - back-02
      # - back-03
    restart: unless-stopped
